# This file was generated by GoReleaser. DO NOT EDIT.
cask "mini-claude" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "8ac88e1702c74dca86913b01931dd00a2d6e5dcb649e377771f727211e7baaf5"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6543c9098efe78d54f6034dd86b32f4b5146fa8e43a2938a181f86c1866344e3"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "71940c0ada98646c59041b25794118934ab30f28130c15af382389494ce773a9"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ef2733044f978330c54bce54fa64d1699e96e0f2d5b5647c918731c9bbe0eb3b"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Linux_arm64.tar.gz"
    end
  end

  name "mini-claude"
  desc "A fast, private TUI chat client for self-hosted LLMs."
  homepage "https://miniclaude.fr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mini-claude"

  # No zap stanza required

end
