# This file was generated by GoReleaser. DO NOT EDIT.
cask "mini-claude" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "5b03cac460102034a469b79a4b62457d11d1d6a47fd2b26d3c54d1628ca95b62"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d08abdb9250a38510fe7a0888d6c8d7efff11866e7a937e80b522291ac5f67e4"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "97b84a17c6366f9e90507aa4584dbcfe0b91a596ce594325ef82f0e398da18c5"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "15c8d6056987e42c177ccab53dc74ebe71eefd9e88d8036b4a6a288af144c49e"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Linux_arm64.tar.gz"
    end
  end

  name "mini-claude"
  desc "A fast, private TUI chat client for self-hosted LLMs."
  homepage "https://miniclaude.fr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mini-claude"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/mini-claude"]
    end
  end

  # No zap stanza required

end
