# This file was generated by GoReleaser. DO NOT EDIT.
cask "mini-claude" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "0a3fdcc22b74894438e7de5b7efa8a3b3d0bd1ffe2e1c1fd356dfdaafe14ef69"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "50d03ff8ab8fcbc50a5d26ea9c3948731b024573421c9a36ae2116b88d975adf"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c7a68fdf1f05a88aeefe7fc4db93581ff70ff11fa9715e41d38f7672bedc931c"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "da3f0b08e5295f3a1a80c15cdcb9e1e0378cc5caf66ffcf7eed452b8059ac2af"
      url "https://github.com/KilianLhy/mini-claude-go/releases/download/v#{version}/mini-claude_Linux_arm64.tar.gz"
    end
  end

  name "mini-claude"
  desc "A fast, private TUI chat client for self-hosted LLMs."
  homepage "https://miniclaude.fr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mini-claude"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/mini-claude"]
    end
  end

  # No zap stanza required

end
